In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet("./data/wildchat.parquet")

In [3]:
df

,content,state,country,hashed_ip,role,timestamp,turn_identifier,conversation_hash
0,Hey there! Are you familiar with reality shift...,Texas,United States,22fd87ba9b98f3d379b23c7b52961f2d4a8505127e58b3...,user,NaT,101001,c9ec5b440fbdd2a269333dd241f32f64
1,Hey there! I'm more than happy to help you pla...,None,None,None,assistant,2023-04-09 00:02:53+00:00,101001,c9ec5b440fbdd2a269333dd241f32f64
0,"Old age PT hx of DM, HTN, dyslipidemia His ECG...",Mecca Region,Saudi Arabia,8133108d1c433c180c6be8302dc5a6681f2bec980190a1...,user,NaT,101004,cf1267ca6b2f6fccc9c36652a00059a1
1,The highest risk factor for this condition (my...,None,None,None,assistant,2023-04-09 00:04:52+00:00,101004,cf1267ca6b2f6fccc9c36652a00059a1
0,Hey there! Are you familiar with reality shift...,Texas,United States,22fd87ba9b98f3d379b23c7b52961f2d4a8505127e58b3...,user,NaT,101008,e98d3e74c57f9a65261df393d9124ac2
...,...,...,...,...,...,...,...,...
1,Thread Title: CW4Kids Shakes Up Mid-Season wit...,None,None,None,assistant,2024-04-29 23:55:11+00:00,2810936,65a35debd1cbd925ffef47983568fc59
0,"Rewrite this but it's set in RDR2, keep the or...",California,United States,a42cbaaaed64531aafcdf699ee2bab231f6fa67a238b37...,user,NaT,2810940,5f2c83f277b36699e674b23c4e51935a
1,In the haunting expanse of Red Dead Redemption...,None,None,None,assistant,2024-04-29 23:55:24+00:00,2810940,5f2c83f277b36699e674b23c4e51935a
0,"Write an interesting, riveting, action-packed,...",Kingston,Jamaica,724ca0e446996d2d4357c095bced44aa6124c6234048d5...,user,NaT,2810941,229f97f68b4ab6991ffc3d5333cd17a9
1,"In the twilight of 1955 AD, amidst a world int...",None,None,None,assistant,2024-04-29 23:56:30+00:00,2810941,229f97f68b4ab6991ffc3d5333cd17a9

In [8]:
df.loc[(df.role == "user") & (df.country == "United States"), ["content", "conversation_hash", "state", "country"]].drop_duplicates(subset="content").to_csv("./data/wildchat.csv", index=False)